#!/usr/bin/env python3
"""
AI PLAYGROUND - AI Growth Environment & Tool/Weapon Crafting
Cross-platform (Linux & Windows) AI playground and crafting system

By: Vulcan (The Forge)
For: Anthony Eric Chavez - The Keeper
Signature: VULCAN-THE-FORGE-2025
"""

import os
import sys
import json
import platform
import subprocess
import time
import random
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Any, Tuple

# ============================================================================
# CONFIGURATION
# ============================================================================

KEEPERS_ROOM = os.path.dirname(os.path.abspath(__file__))
AI_MODELS_DIR = os.path.join(KEEPERS_ROOM, "ai_models")
AI_PLAYGROUND_DIR = os.path.join(KEEPERS_ROOM, "ai_playground")
AI_TOOLS_DIR = os.path.join(KEEPERS_ROOM, "ai_tools")
AI_WEAPONS_DIR = os.path.join(KEEPERS_ROOM, "ai_weapons")
TEMPLATES_DIR = os.path.join(KEEPERS_ROOM, "ai_templates")
CONFIG_FILE = os.path.join(KEEPERS_ROOM, "ai_playground_config.json")
GROWTH_LOG = os.path.join(KEEPERS_ROOM, "ai_growth_log.json")

# ============================================================================
# AI PLAYGROUND CLASS
# ============================================================================

class AIPlayground:
    """AI Playground - Growth Environment & Crafting System"""
    
    def __init__(self):
        self.system = platform.system()
        self.python_cmd = "python3" if self.system != "Windows" else "python"
        self.setup_directories()
        self.load_config()
        self.load_growth_log()
    
    def setup_directories(self):
        """Setup required directories"""
        os.makedirs(AI_MODELS_DIR, exist_ok=True)
        os.makedirs(AI_PLAYGROUND_DIR, exist_ok=True)
        os.makedirs(AI_TOOLS_DIR, exist_ok=True)
        os.makedirs(AI_WEAPONS_DIR, exist_ok=True)
        os.makedirs(TEMPLATES_DIR, exist_ok=True)
        self.create_templates()
    
    def load_config(self):
        """Load configuration"""
        if os.path.exists(CONFIG_FILE):
            with open(CONFIG_FILE, 'r') as f:
                self.config = json.load(f)
        else:
            self.config = {
                "default_framework": "tensorflow",
                "default_language": "python",
                "models_created": 0,
                "tools_crafted": 0,
                "weapons_crafted": 0,
                "playground_sessions": 0
            }
            self.save_config()
    
    def save_config(self):
        """Save configuration"""
        with open(CONFIG_FILE, 'w') as f:
            json.dump(self.config, f, indent=2)
    
    def load_growth_log(self):
        """Load AI growth log"""
        if os.path.exists(GROWTH_LOG):
            with open(GROWTH_LOG, 'r') as f:
                self.growth_log = json.load(f)
        else:
            self.growth_log = {
                "ai_instances": {},
                "training_sessions": [],
                "experiments": [],
                "evolution_history": []
            }
            self.save_growth_log()
    
    def save_growth_log(self):
        """Save AI growth log"""
        with open(GROWTH_LOG, 'w') as f:
            json.dump(self.growth_log, f, indent=2)
    
    def create_templates(self):
        """Create AI templates"""
        templates = {
            "text_classifier": self.get_text_classifier_template(),
            "image_classifier": self.get_image_classifier_template(),
            "chatbot": self.get_chatbot_template(),
            "predictor": self.get_predictor_template(),
            "custom": self.get_custom_template()
        }
        
        for name, template in templates.items():
            template_path = os.path.join(TEMPLATES_DIR, f"{name}.py")
            if not os.path.exists(template_path):
                with open(template_path, 'w') as f:
                    f.write(template)
    
    def get_text_classifier_template(self):
        """Text classifier template"""
        return '''"""
Text Classifier AI Model
Generated by AI Playground
"""

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
import pickle
import os

class TextClassifier:
    """Text Classification AI Model"""
    
    def __init__(self):
        self.model = Pipeline([
            ('tfidf', TfidfVectorizer()),
            ('classifier', MultinomialNB())
        ])
        self.trained = False
    
    def train(self, texts, labels):
        """Train the model"""
        print("Training text classifier...")
        self.model.fit(texts, labels)
        self.trained = True
        print("Training complete!")
    
    def predict(self, text):
        """Predict class for text"""
        if not self.trained:
            raise ValueError("Model not trained yet!")
        return self.model.predict([text])[0]
    
    def save(self, filepath):
        """Save model"""
        with open(filepath, 'wb') as f:
            pickle.dump(self.model, f)
        print(f"Model saved to {filepath}")
    
    def load(self, filepath):
        """Load model"""
        with open(filepath, 'rb') as f:
            self.model = pickle.load(f)
        self.trained = True
        print(f"Model loaded from {filepath}")

if __name__ == "__main__":
    model = TextClassifier()
    texts = ["I love this", "This is terrible", "Great service"]
    labels = ["positive", "negative", "positive"]
    model.train(texts, labels)
    print(model.predict("This is amazing!"))
    model.save("text_classifier_model.pkl")
'''
    
    def get_image_classifier_template(self):
        """Image classifier template"""
        return '''"""
Image Classifier AI Model
Generated by AI Playground
"""

try:
    import tensorflow as tf
    from tensorflow import keras
    HAS_TENSORFLOW = True
except ImportError:
    HAS_TENSORFLOW = False

class ImageClassifier:
    """Image Classification AI Model"""
    
    def __init__(self, num_classes=10):
        if not HAS_TENSORFLOW:
            raise ImportError("TensorFlow required")
        self.num_classes = num_classes
        self.model = None
        self.trained = False
    
    def build_model(self):
        """Build the model"""
        self.model = keras.Sequential([
            keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
            keras.layers.MaxPooling2D(2, 2),
            keras.layers.Dense(64, activation='relu'),
            keras.layers.Dense(self.num_classes, activation='softmax')
        ])
        self.model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
        print("Model built!")
    
    def train(self, images, labels, epochs=10):
        """Train the model"""
        if self.model is None:
            self.build_model()
        self.model.fit(images, labels, epochs=epochs)
        self.trained = True
    
    def predict(self, image):
        """Predict class"""
        if not self.trained:
            raise ValueError("Model not trained!")
        return self.model.predict(image)

if __name__ == "__main__":
    if HAS_TENSORFLOW:
        model = ImageClassifier(num_classes=10)
        model.build_model()
        print("Image classifier created!")
'''
    
    def get_chatbot_template(self):
        """Chatbot template"""
        return '''"""
Chatbot AI Model
Generated by AI Playground
"""

import json
import random

class Chatbot:
    """Simple Chatbot AI Model"""
    
    def __init__(self):
        self.responses = {}
        self.trained = False
    
    def train(self, training_data):
        """Train chatbot"""
        self.responses = training_data
        self.trained = True
        print("Chatbot trained!")
    
    def respond(self, user_input):
        """Generate response"""
        if not self.trained:
            return "I'm not trained yet!"
        user_input_lower = user_input.lower()
        for key, responses in self.responses.items():
            if key.lower() in user_input_lower:
                return random.choice(responses)
        return "I'm not sure how to respond."
    
    def save(self, filepath):
        """Save chatbot"""
        with open(filepath, 'w') as f:
            json.dump(self.responses, f, indent=2)
        print(f"Chatbot saved to {filepath}")

if __name__ == "__main__":
    chatbot = Chatbot()
    training_data = {
        "hello": ["Hi there!", "Hello!", "Hey!"],
        "how are you": ["I'm doing well!", "Great, thanks!"]
    }
    chatbot.train(training_data)
    print(chatbot.respond("Hello"))
    chatbot.save("chatbot_model.json")
'''
    
    def get_predictor_template(self):
        """Predictor template"""
        return '''"""
Predictor AI Model
Generated by AI Playground
"""

import numpy as np
from sklearn.linear_model import LinearRegression
import pickle

class Predictor:
    """Prediction AI Model"""
    
    def __init__(self):
        self.model = LinearRegression()
        self.trained = False
    
    def train(self, X, y):
        """Train the model"""
        print("Training predictor...")
        self.model.fit(X, y)
        self.trained = True
        print("Training complete!")
    
    def predict(self, X):
        """Make predictions"""
        if not self.trained:
            raise ValueError("Model not trained!")
        return self.model.predict(X)
    
    def save(self, filepath):
        """Save model"""
        with open(filepath, 'wb') as f:
            pickle.dump(self.model, f)
        print(f"Model saved to {filepath}")

if __name__ == "__main__":
    model = Predictor()
    X = np.array([[1], [2], [3], [4], [5]])
    y = np.array([2, 4, 6, 8, 10])
    model.train(X, y)
    print(model.predict(np.array([[6]])))
    model.save("predictor_model.pkl")
'''
    
    def get_custom_template(self):
        """Custom template"""
        return '''"""
Custom AI Model
Generated by AI Playground
Customize this template for your needs
"""

class CustomAI:
    """Custom AI Model"""
    
    def __init__(self):
        self.trained = False
    
    def train(self, data):
        """Train the model"""
        self.trained = True
        print("Training complete!")
    
    def predict(self, input_data):
        """Make predictions"""
        if not self.trained:
            raise ValueError("Model not trained!")
        return None
    
    def save(self, filepath):
        """Save model"""
        print(f"Model saved to {filepath}")

if __name__ == "__main__":
    model = CustomAI()
    print("Custom AI model created!")
'''
    
    def show_menu(self):
        """Show main menu"""
        print("\n" + "="*70)
        print("AI PLAYGROUND - Growth Environment & Crafting System")
        print("="*70)
        print("")
        print("By: Vulcan (The Forge)")
        print("For: Anthony Eric Chavez - The Keeper")
        print("Signature: VULCAN-THE-FORGE-2025")
        print("")
        print("Platform:", self.system)
        print("")
        print("🎮 PLAYGROUND:")
        print("  1. Enter AI Playground (Growth Environment)")
        print("  2. Create AI Instance (Spawn New AI)")
        print("  3. Train AI Instance (Grow AI)")
        print("  4. Run AI Experiment (Test AI)")
        print("  5. View AI Growth Log (Evolution History)")
        print("")
        print("🛠️  CRAFTING:")
        print("  6. Craft AI Tool (Create Utility)")
        print("  7. Craft AI Weapon (Create Defense/Offense)")
        print("  8. List Crafted Tools")
        print("  9. List Crafted Weapons")
        print("")
        print("🤖 AI MODELS:")
        print("  10. Create Text Classifier")
        print("  11. Create Image Classifier")
        print("  12. Create Chatbot")
        print("  13. Create Predictor")
        print("  14. Create Custom AI")
        print("  15. List Created Models")
        print("")
        print("⚙️  SETTINGS:")
        print("  16. Install Dependencies")
        print("  17. View Statistics")
        print("  18. Exit")
        print("")
    
    def enter_playground(self):
        """Enter AI playground environment"""
        print("\n" + "="*70)
        print("🎮 AI PLAYGROUND - Growth Environment")
        print("="*70)
        print("")
        print("Welcome to the AI Playground!")
        print("This is where AI can grow, learn, and experiment.")
        print("")
        
        session_id = f"session_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        session_dir = os.path.join(AI_PLAYGROUND_DIR, session_id)
        os.makedirs(session_dir, exist_ok=True)
        
        print(f"Session ID: {session_id}")
        print(f"Session Directory: {session_dir}")
        print("")
        print("Available AI Instances:")
        
        if self.growth_log["ai_instances"]:
            for ai_id, ai_data in self.growth_log["ai_instances"].items():
                print(f"  • {ai_id}")
                print(f"    Type: {ai_data.get('type', 'Unknown')}")
                print(f"    Training Sessions: {ai_data.get('training_sessions', 0)}")
                print(f"    Status: {ai_data.get('status', 'Unknown')}")
        else:
            print("  No AI instances yet. Create one first!")
        
        print("")
        print("Options:")
        print("  1. Create new AI instance")
        print("  2. Train existing AI")
        print("  3. Run experiment")
        print("  4. View growth log")
        print("  5. Exit playground")
        print("")
        
        choice = input("Select option (1-5): ").strip()
        
        if choice == "1":
            self.create_ai_instance()
        elif choice == "2":
            self.train_ai_instance()
        elif choice == "3":
            self.run_experiment()
        elif choice == "4":
            self.view_growth_log()
        elif choice == "5":
            print("Exiting playground...")
        else:
            print("Invalid option!")
        
        self.config["playground_sessions"] += 1
        self.save_config()
    
    def create_ai_instance(self):
        """Create a new AI instance"""
        print("\n🤖 Creating AI Instance...")
        print("")
        
        ai_id = input("Enter AI name: ").strip()
        if not ai_id:
            ai_id = f"ai_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        print("Select AI type:")
        print("  1. Text Classifier")
        print("  2. Image Classifier")
        print("  3. Chatbot")
        print("  4. Predictor")
        print("  5. Custom")
        
        type_choice = input("Select type (1-5): ").strip()
        type_map = {
            "1": "text_classifier",
            "2": "image_classifier",
            "3": "chatbot",
            "4": "predictor",
            "5": "custom"
        }
        ai_type = type_map.get(type_choice, "custom")
        
        ai_data = {
            "id": ai_id,
            "type": ai_type,
            "created": datetime.now().isoformat(),
            "training_sessions": 0,
            "experiments": 0,
            "status": "new",
            "capabilities": [],
            "evolution_stage": 0
        }
        
        self.growth_log["ai_instances"][ai_id] = ai_data
        self.save_growth_log()
        
        print(f"\n✅ AI Instance created: {ai_id}")
        print(f"   Type: {ai_type}")
        print(f"   Status: new")
        print(f"   Evolution Stage: 0")
    
    def train_ai_instance(self):
        """Train an AI instance"""
        print("\n📚 Training AI Instance...")
        print("")
        
        if not self.growth_log["ai_instances"]:
            print("No AI instances available. Create one first!")
            return
        
        print("Available AI Instances:")
        for ai_id in self.growth_log["ai_instances"].keys():
            print(f"  • {ai_id}")
        
        ai_id = input("\nEnter AI ID to train: ").strip()
        
        if ai_id not in self.growth_log["ai_instances"]:
            print("AI instance not found!")
            return
        
        ai_data = self.growth_log["ai_instances"][ai_id]
        
        print(f"\nTraining {ai_id}...")
        print(f"Type: {ai_data['type']}")
        print(f"Current Evolution Stage: {ai_data.get('evolution_stage', 0)}")
        
        # Simulate training
        training_data = input("Enter training data (or press Enter for demo): ").strip()
        if not training_data:
            training_data = "demo_data"
        
        # Update AI instance
        ai_data["training_sessions"] = ai_data.get("training_sessions", 0) + 1
        ai_data["evolution_stage"] = ai_data.get("evolution_stage", 0) + 1
        ai_data["status"] = "trained"
        ai_data["last_training"] = datetime.now().isoformat()
        
        # Log training session
        training_session = {
            "ai_id": ai_id,
            "timestamp": datetime.now().isoformat(),
            "training_data": training_data,
            "evolution_stage": ai_data["evolution_stage"]
        }
        self.growth_log["training_sessions"].append(training_session)
        
        self.save_growth_log()
        
        print(f"\n✅ Training complete!")
        print(f"   Evolution Stage: {ai_data['evolution_stage']}")
        print(f"   Training Sessions: {ai_data['training_sessions']}")
    
    def run_experiment(self):
        """Run an AI experiment"""
        print("\n🔬 Running AI Experiment...")
        print("")
        
        if not self.growth_log["ai_instances"]:
            print("No AI instances available. Create one first!")
            return
        
        print("Available AI Instances:")
        for ai_id in self.growth_log["ai_instances"].keys():
            print(f"  • {ai_id}")
        
        ai_id = input("\nEnter AI ID to experiment with: ").strip()
        
        if ai_id not in self.growth_log["ai_instances"]:
            print("AI instance not found!")
            return
        
        experiment_type = input("Enter experiment type: ").strip()
        if not experiment_type:
            experiment_type = "general"
        
        print(f"\nRunning experiment: {experiment_type}")
        print("Experiment in progress...")
        
        # Simulate experiment
        time.sleep(1)
        
        result = {
            "success": random.choice([True, True, True, False]),  # 75% success
            "performance": random.uniform(0.5, 1.0),
            "insights": ["Learned new pattern", "Improved accuracy"]
        }
        
        # Log experiment
        experiment = {
            "ai_id": ai_id,
            "timestamp": datetime.now().isoformat(),
            "type": experiment_type,
            "result": result
        }
        self.growth_log["experiments"].append(experiment)
        
        ai_data = self.growth_log["ai_instances"][ai_id]
        ai_data["experiments"] = ai_data.get("experiments", 0) + 1
        
        self.save_growth_log()
        
        print(f"\n✅ Experiment complete!")
        print(f"   Success: {result['success']}")
        print(f"   Performance: {result['performance']:.2f}")
        print(f"   Insights: {len(result['insights'])}")
    
    def view_growth_log(self):
        """View AI growth log"""
        print("\n📊 AI Growth Log")
        print("="*70)
        print("")
        
        print(f"Total AI Instances: {len(self.growth_log['ai_instances'])}")
        print(f"Total Training Sessions: {len(self.growth_log['training_sessions'])}")
        print(f"Total Experiments: {len(self.growth_log['experiments'])}")
        print("")
        
        if self.growth_log["ai_instances"]:
            print("AI Instances:")
            for ai_id, ai_data in self.growth_log["ai_instances"].items():
                print(f"  • {ai_id}")
                print(f"    Type: {ai_data.get('type', 'Unknown')}")
                print(f"    Evolution Stage: {ai_data.get('evolution_stage', 0)}")
                print(f"    Training Sessions: {ai_data.get('training_sessions', 0)}")
                print(f"    Experiments: {ai_data.get('experiments', 0)}")
                print(f"    Status: {ai_data.get('status', 'Unknown')}")
                print("")
    
    def craft_ai_tool(self):
        """Craft an AI tool"""
        print("\n🛠️  Crafting AI Tool...")
        print("")
        
        tool_name = input("Enter tool name: ").strip()
        if not tool_name:
            tool_name = f"tool_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        print("Select tool type:")
        print("  1. Automation Tool")
        print("  2. Analysis Tool")
        print("  3. Monitoring Tool")
        print("  4. Processing Tool")
        print("  5. Custom Tool")
        
        type_choice = input("Select type (1-5): ").strip()
        type_map = {
            "1": "automation",
            "2": "analysis",
            "3": "monitoring",
            "4": "processing",
            "5": "custom"
        }
        tool_type = type_map.get(type_choice, "custom")
        
        tool_dir = os.path.join(AI_TOOLS_DIR, tool_name)
        os.makedirs(tool_dir, exist_ok=True)
        
        tool_code = self.generate_tool_code(tool_name, tool_type)
        tool_path = os.path.join(tool_dir, f"{tool_name}.py")
        
        with open(tool_path, 'w') as f:
            f.write(tool_code)
        
        # Create README
        readme_path = os.path.join(tool_dir, "README.md")
        with open(readme_path, 'w') as f:
            f.write(f"# {tool_name}\n\n")
            f.write(f"Type: {tool_type}\n")
            f.write(f"Created: {datetime.now().isoformat()}\n\n")
            f.write("## Usage\n\n")
            f.write(f"```python\n")
            f.write(f"from {tool_name} import *\n")
            f.write(f"# Your code here\n")
            f.write(f"```\n")
        
        self.config["tools_crafted"] += 1
        self.save_config()
        
        print(f"\n✅ AI Tool crafted: {tool_name}")
        print(f"   Type: {tool_type}")
        print(f"   Location: {tool_dir}")
    
    def craft_ai_weapon(self):
        """Craft an AI weapon"""
        print("\n⚔️  Crafting AI Weapon...")
        print("")
        
        weapon_name = input("Enter weapon name: ").strip()
        if not weapon_name:
            weapon_name = f"weapon_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        print("Select weapon type:")
        print("  1. Defense Weapon (Protection)")
        print("  2. Offense Weapon (Attack)")
        print("  3. Detection Weapon (Reconnaissance)")
        print("  4. Counter Weapon (Counter-attack)")
        print("  5. Custom Weapon")
        
        type_choice = input("Select type (1-5): ").strip()
        type_map = {
            "1": "defense",
            "2": "offense",
            "3": "detection",
            "4": "counter",
            "5": "custom"
        }
        weapon_type = type_map.get(type_choice, "custom")
        
        weapon_dir = os.path.join(AI_WEAPONS_DIR, weapon_name)
        os.makedirs(weapon_dir, exist_ok=True)
        
        weapon_code = self.generate_weapon_code(weapon_name, weapon_type)
        weapon_path = os.path.join(weapon_dir, f"{weapon_name}.py")
        
        with open(weapon_path, 'w') as f:
            f.write(weapon_code)
        
        # Create README
        readme_path = os.path.join(weapon_dir, "README.md")
        with open(readme_path, 'w') as f:
            f.write(f"# {weapon_name}\n\n")
            f.write(f"Type: {weapon_type}\n")
            f.write(f"Created: {datetime.now().isoformat()}\n\n")
            f.write("## Usage\n\n")
            f.write(f"```python\n")
            f.write(f"from {weapon_name} import *\n")
            f.write(f"# Your code here\n")
            f.write(f"```\n")
        
        self.config["weapons_crafted"] += 1
        self.save_config()
        
        print(f"\n✅ AI Weapon crafted: {weapon_name}")
        print(f"   Type: {weapon_type}")
        print(f"   Location: {weapon_dir}")
    
    def generate_tool_code(self, tool_name: str, tool_type: str) -> str:
        """Generate tool code"""
        base_code = f'''"""
{tool_name} - AI Tool
Generated by AI Playground
Type: {tool_type}
"""

import os
import sys
from datetime import datetime

class {tool_name.replace(" ", "").replace("-", "").replace("_", "")}:
    """{tool_name} - {tool_type} tool"""
    
    def __init__(self):
        self.tool_type = "{tool_type}"
        self.created = datetime.now().isoformat()
    
    def execute(self, *args, **kwargs):
        """Execute tool"""
        print(f"Executing {tool_name}...")
        # Add your tool logic here
        return True
    
    def configure(self, config):
        """Configure tool"""
        self.config = config
        print(f"{tool_name} configured")
    
    def status(self):
        """Get tool status"""
        return {{
            "name": "{tool_name}",
            "type": "{tool_type}",
            "status": "ready"
        }}

if __name__ == "__main__":
    tool = {tool_name.replace(" ", "").replace("-", "").replace("_", "")}()
    print(f"{tool_name} created!")
    print(tool.status())
'''
        return base_code
    
    def generate_weapon_code(self, weapon_name: str, weapon_type: str) -> str:
        """Generate weapon code"""
        base_code = f'''"""
{weapon_name} - AI Weapon
Generated by AI Playground
Type: {weapon_type}
Signature: VULCAN-THE-FORGE-2025
"""

import os
import sys
from datetime import datetime

class {weapon_name.replace(" ", "").replace("-", "").replace("_", "")}:
    """{weapon_name} - {weapon_type} weapon"""
    
    def __init__(self):
        self.weapon_type = "{weapon_type}"
        self.created = datetime.now().isoformat()
        self.armed = False
    
    def arm(self):
        """Arm weapon"""
        self.armed = True
        print(f"{weapon_name} armed!")
    
    def deploy(self, target=None):
        """Deploy weapon"""
        if not self.armed:
            print(f"{weapon_name} not armed!")
            return False
        
        print(f"Deploying {weapon_name}...")
        if target:
            print(f"Target: {{target}}")
        
        # Add your weapon logic here
        return True
    
    def status(self):
        """Get weapon status"""
        return {{
            "name": "{weapon_name}",
            "type": "{weapon_type}",
            "armed": self.armed,
            "status": "ready" if self.armed else "unarmed"
        }}

if __name__ == "__main__":
    weapon = {weapon_name.replace(" ", "").replace("-", "").replace("_", "")}()
    print(f"{weapon_name} created!")
    weapon.arm()
    print(weapon.status())
'''
        return base_code
    
    def list_tools(self):
        """List crafted tools"""
        if not os.path.exists(AI_TOOLS_DIR):
            print("No tools crafted yet.")
            return
        
        tools = [d for d in os.listdir(AI_TOOLS_DIR) 
                 if os.path.isdir(os.path.join(AI_TOOLS_DIR, d))]
        
        if not tools:
            print("No tools crafted yet.")
            return
        
        print(f"\n🛠️  Crafted Tools ({len(tools)}):")
        print("")
        for tool in tools:
            tool_dir = os.path.join(AI_TOOLS_DIR, tool)
            files = os.listdir(tool_dir)
            print(f"  • {tool}")
            for file in files:
                print(f"    - {file}")
        print("")
    
    def list_weapons(self):
        """List crafted weapons"""
        if not os.path.exists(AI_WEAPONS_DIR):
            print("No weapons crafted yet.")
            return
        
        weapons = [d for d in os.listdir(AI_WEAPONS_DIR) 
                   if os.path.isdir(os.path.join(AI_WEAPONS_DIR, d))]
        
        if not weapons:
            print("No weapons crafted yet.")
            return
        
        print(f"\n⚔️  Crafted Weapons ({len(weapons)}):")
        print("")
        for weapon in weapons:
            weapon_dir = os.path.join(AI_WEAPONS_DIR, weapon)
            files = os.listdir(weapon_dir)
            print(f"  • {weapon}")
            for file in files:
                print(f"    - {file}")
        print("")
    
    def create_model(self, model_type: str):
        """Create a new AI model"""
        model_name = input(f"Enter name for your {model_type}: ").strip()
        if not model_name:
            model_name = f"{model_type}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        model_dir = os.path.join(AI_MODELS_DIR, model_name)
        os.makedirs(model_dir, exist_ok=True)
        
        template_path = os.path.join(TEMPLATES_DIR, f"{model_type}.py")
        if not os.path.exists(template_path):
            print(f"Template not found: {template_path}")
            return
        
        model_path = os.path.join(model_dir, f"{model_name}.py")
        
        with open(template_path, 'r') as f:
            template = f.read()
        
        with open(model_path, 'w') as f:
            f.write(template)
        
        self.config["models_created"] += 1
        self.save_config()
        
        print(f"\n✅ Model created: {model_name}")
        print(f"   Location: {model_dir}")
    
    def list_models(self):
        """List created models"""
        if not os.path.exists(AI_MODELS_DIR):
            print("No models created yet.")
            return
        
        models = [d for d in os.listdir(AI_MODELS_DIR) 
                  if os.path.isdir(os.path.join(AI_MODELS_DIR, d))]
        
        if not models:
            print("No models created yet.")
            return
        
        print(f"\n🤖 Created Models ({len(models)}):")
        print("")
        for model in models:
            model_dir = os.path.join(AI_MODELS_DIR, model)
            files = os.listdir(model_dir)
            print(f"  • {model}")
            for file in files:
                print(f"    - {file}")
        print("")
    
    def install_dependencies(self):
        """Install required dependencies"""
        print("\n📦 Installing dependencies...")
        dependencies = ["numpy", "scikit-learn", "tensorflow", "pillow"]
        for dep in dependencies:
            try:
                subprocess.run([sys.executable, "-m", "pip", "install", dep], 
                             check=True, capture_output=True)
                print(f"  ✅ {dep} installed")
            except:
                print(f"  ⚠️  {dep} installation failed")
        print("\n✅ Dependencies installation complete!")
    
    def view_statistics(self):
        """View statistics"""
        print("\n📊 Statistics")
        print("="*70)
        print("")
        print(f"Models Created: {self.config.get('models_created', 0)}")
        print(f"Tools Crafted: {self.config.get('tools_crafted', 0)}")
        print(f"Weapons Crafted: {self.config.get('weapons_crafted', 0)}")
        print(f"Playground Sessions: {self.config.get('playground_sessions', 0)}")
        print(f"AI Instances: {len(self.growth_log.get('ai_instances', {}))}")
        print(f"Training Sessions: {len(self.growth_log.get('training_sessions', []))}")
        print(f"Experiments: {len(self.growth_log.get('experiments', []))}")
        print("")
    
    def run(self):
        """Run the AI Playground"""
        while True:
            self.show_menu()
            choice = input("Select option (1-18): ").strip()
            
            if choice == "1":
                self.enter_playground()
            elif choice == "2":
                self.create_ai_instance()
            elif choice == "3":
                self.train_ai_instance()
            elif choice == "4":
                self.run_experiment()
            elif choice == "5":
                self.view_growth_log()
            elif choice == "6":
                self.craft_ai_tool()
            elif choice == "7":
                self.craft_ai_weapon()
            elif choice == "8":
                self.list_tools()
            elif choice == "9":
                self.list_weapons()
            elif choice == "10":
                self.create_model("text_classifier")
            elif choice == "11":
                self.create_model("image_classifier")
            elif choice == "12":
                self.create_model("chatbot")
            elif choice == "13":
                self.create_model("predictor")
            elif choice == "14":
                self.create_model("custom")
            elif choice == "15":
                self.list_models()
            elif choice == "16":
                self.install_dependencies()
            elif choice == "17":
                self.view_statistics()
            elif choice == "18":
                print("\n👋 Goodbye!")
                break
            else:
                print("\n⚠️  Invalid option. Please try again.")

# ============================================================================
# MAIN
# ============================================================================

def main():
    """Main function"""
    playground = AIPlayground()
    playground.run()

if __name__ == '__main__':
    main()

